server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
        - id: ecommerceModule
          uri: lb://ecommerce
          predicates:
          - Path=/ecommerce/**
        - id: providerModule
          uri: lb://provider
          predicates:
          - Path=/provider/**
        - id: shippingModule
          uri: lb://shipping
          predicates:
          - Path=/shipping/**